#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
#nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_INTERNAL_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_LOG_DIR/server.log 2>&1 &
. ${OPENSHIFT_DATA_DIR}diy_env.sh
cd ${OPENSHIFT_REPO_DIR}
# Extract node.js script from package.json
APP_FILE=`node -e 'var package=require("./package.json");console.log(package.scripts.start.split(/ /)[1]);'`
# Backup server.log if exist
LOG_FILE=${OPENSHIFT_DIY_LOG_DIR}server.log
if [ -s $LOG_FILE ]; then
  # Get the modify time of the log file
  MODIFY=`stat -c "%Y" $LOG_FILE`
  # Convert to time stamp
  STAMP=`date -d @$MODIFY "+%Y%m%d-%H%M%S"`
  mv -f $LOG_FILE ${LOG_FILE}.log.${STAMP}
fi
# Backup redis.log if exist
REDIS_LOG_FILE=${OPENSHIFT_DIY_LOG_DIR}redis.log
if [ -s $REDIS_LOG_FILE ]; then
  # Get the modify time of the log file
  MODIFY=`stat -c "%Y" $REDIS_LOG_FILE`
  # Convert to time stamp
  STAMP=`date -d @$MODIFY "+%Y%m%d-%H%M%S"`
  mv -f $REDIS_LOG_FILE ${REDIS_LOG_FILE}.log.${STAMP}
fi
echo "Node Version:"
node -e 'console.log(process.versions);'
echo "Redis Version:"
redis-cli --version

# Start Redis server
redis-server ${OPENSHIFT_DATA_DIR}/redis-${REDIS_VERSION}/redis.conf

# Use supervisor to keep node app running after crash
echo "nohup supervisor $APP_FILE >$LOG_FILE 2>&1 &"
nohup supervisor -w $APP_FILE $APP_FILE >$LOG_FILE 2>&1 &
